# Generated by Django 2.1.4 on 2018-12-06 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dane',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nazwa', models.CharField(max_length=15)),
                ('data', models.CharField(max_length=40)),
                ('cena', models.IntegerField()),
            ],
        ),
    ]
