# Generated by Django 2.1.4 on 2018-12-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projekt', '0002_auto_20181206_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dane',
            name='cena',
            field=models.FloatField(),
        ),
    ]
